Alchuang22-dev/DEC_sustainable_diet_helper

frontend/pagesNews/video_detail/video_detail.vue

更新video的后端格式

---

frontend/pages.json
frontend/pages/index/index.vue
frontend/pagesTool/home_servant/home_servant.vue
frontend/pagesTool/nutrition_calculator/nutrition_calculator.vue

由openfront的网页改进而来，只实现了基础功能，没写后端适配

更新营养计算和家庭菜谱框架

---

frontend/pages/index/index.vue
frontend/pagesMy/appSettings/appSettings.vue
frontend/pagesMy/favorites/favorites.vue
frontend/pagesMy/userSettings/userSettings.vue

更新了三个子页面的框架

---

frontend/pagesTool/add_food/add_food.vue
frontend/pagesTool/carbon_calculator/carbon_calculator.vue
frontend/pagesTool/modify_food/modify_food.vue

计算器界面，修改修改食物界面，适应更改。

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesMy/setGoals/setGoals.vue

完成设置目标的前端部分。实现了如下效果：
- 用户现在可以设置营养目标，支持（能量、蛋白质、碳水化合物、钠、脂肪）
- 追加了多语言支持。
未添加后端页面，不会影响现有功能

feat(setGoals): setgoals设置目标 frontend

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesMy/foodPreferences/foodPreferences.json
frontend/pagesMy/foodPreferences/foodPreferences.vue

Remake food reference page. 添加的改动如下：
- 新加入了10种food reference及其在数据库中的具体含义（在foodreference.json内）
- 修复了foodreference.vue的页面滚动bug
- 为新功能添加多语言支持

refactor($foodreference): remake food reference page

---

frontend/pages/static/close.svg
frontend/pagesTool/carbon_calculator/carbon_calculator.vue

重置碳计算器食物卡片中的按钮样式。
图标似乎无法正常显示，明天修改。

fix($calculator): reset button type

---

frontend/pagesTool/food_recommend/food_recommend.vue

Add new function to recommend tools. 变化如下：
- 新功能：喜欢菜品与不感兴趣
- 用户可以通过“喜欢菜品”提升其在推荐算法中的权重
- 用户可以通过“不感兴趣”降低其在推荐算法中的权重
- 预留了删除和更新菜品的方法

feat($foodRecommend): new function of recommend tools

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesTool/food_recommend/food_recommend.vue

fix($foodrecommend): fix animation bug

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesNews/web_detail/web_detail.vue
frontend/pagesSetting/SoftwareInfo/SoftwareInfo.vue

应相关方要求移除新闻功能。更改如下：
- “新闻”功能更名为“社区”，并不再提供即时资讯服务
- 移除了所有外部链接
PS：关于更改的详细信息，请移步至issue

fix(news): 更改新闻功能

---

backend/Dockerfile
backend/docker-compose.yml
backend/go.mod
backend/init.sql
backend/internal/controllers/family_controller.go
backend/internal/controllers/user_controller.go
backend/nginx.conf

feat: add docker configuration

---

frontend/pages/news_index/news_index.vue
frontend/pagesMy/wechatLogin/wechatLogin.vue
frontend/stores/user.js

修复了微信登录的一些问题。改动如下：
- 增加了登录的api接口
- 增加了管理用户状态的pinia数据库
- 略微修改了新闻页面

fix(login): fix wechat login

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pages.json
frontend/pages/news_index/news_index.vue
frontend/pagesNews/create_news/create_news.vue

修复了微信登录的一些问题。改动如下：
- 增加了登录的api接口
- 增加了管理用户状态的pinia数据库
- 略微修改了新闻页面

feat($createnews): user create news

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/manifest.json
frontend/pagesMy/wechatLogin/wechatLogin.vue
frontend/pagesTool/home_servant/home_servant.vue
frontend/project.config.json

feat(登录): 实现登录功能

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/manifest.json
frontend/pages/my_index/my_index.vue
frontend/pagesMy/foodPreferences/foodPreferences.vue
frontend/pagesTool/food_recommend/food_recommend.vue

fix some bugs.
- 修复my_index登录后跳转异常bug
- 更改了食谱生成ui

fix(login): fix some bugs

---

frontend/pagesTool/modify_food/modify_food.vue

fix（修改食物）：解决修改食物页面类似的输入冲突问题

---

frontend/pagesMy/foodPreferences/foodPreferences.vue
frontend/pagesTool/food_recommend/food_recommend.vue

fix: fix getting token

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesMy/foodPreferences/foodPreferences.vue

修改了食物偏好的实现。进行了以下改动：
- 更新了ui
- 修复了用户无法删除已保存黑名单食物的bug
- 增加了对应的多语言支持

fix(perference): new ui  & bug fix

---

frontend/pages.json
frontend/pages/news_index/news_index.vue
frontend/pagesNews/create_news/create_news.vue
frontend/pagesTool/food_recommend/food_recommend.vue
frontend/pagesTool/recipe/recipe.vue

完成了食谱推荐功能的前后端对接。进行了以下更改：
- 完成保存食材和食谱推荐的前后端更新
- 新建食谱详情页文件
- 修复已登录用户无法进入“写文章”页面的bug
- 修复“写文章”页面无法获取用户头像和昵称的bug
FORESHOW：接下来的commit将会进行以下更改：
- 食材库的多语言支持
- 食谱详情页设计
- 修复用户获取上次食材失败bug

feat(recommend): recipe recommend

---

frontend/pagesSetting/ConnectUs/ConnectUs.vue
frontend/pagesSetting/FeedBack/FeedBack.vue
frontend/pagesSetting/Idinfo/Idinfo.vue
frontend/pagesSetting/Storage/Storage.vue

feat($settings): filling software settings

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pagesSetting/Authorizations/Authorizations.vue
frontend/pagesSetting/Idinfo/Idinfo.vue
frontend/pagesSetting/InfoShared/InfoShared.vue
frontend/pagesSetting/PIConnected/PIConnected.vue
frontend/pagesSetting/Permissions/Permissions.vue

feat($settings): filling user settings

---

frontend/pagesTool/food_recommend/food_recommend.vue

fix(recommend): fix bug

---

frontend/pagesTool/food_recommend/food_recommend.vue

fix(recommend): fit new api

---

frontend/pages/news_index/news_index.vue
frontend/pagesNews/news_detail/news_detail_new.vue
frontend/stores/news_list.js

社区页ui更新。进行了以下改动：
- 移除了tabs分类
- 修复了“写文章”登录状态bug
- 增加了搜索框
- 修改了news_list.js中的相应方法

fix(community): community page

---

frontend/pages.json
frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/edit_draft/edit_draft.vue

实现了草稿编辑器。
进入方法：我的-我的创作-选取卡片点编辑

feat(drafteditor): draft editor

---

frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/create_news/create_news.vue

feat(myhome): check draft

---

frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/create_news/create_news.vue
frontend/pagesNews/edit_draft/edit_draft.vue

实现了草稿编辑器，进行了以下改动：
- 增加了删除草稿的对接
- 增加了编辑草稿的对接
- 修复了图片描述无法正常上传的bug

feat(draft): review draft

---

frontend/pagesNews/edit_draft/edit_draft.vue

feat(draft): update draft

---

frontend/pages.json
frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/preview_draft/preview_draft.vue

feat(draft): preview draft

---

frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/create_news/create_news.vue
frontend/pagesNews/edit_draft/edit_draft.vue
frontend/pagesNews/news_detail/news_detail.vue

增加了新闻视图。进行了以下变化：
- 添加了新闻页面
- 添加了用户创作新闻直接发布的方法
- 更新了更新草稿的方法
- 微调个人主页

feat(news): view post

---

frontend/pages/news_index/news_index.vue
frontend/stores/news_list.js

完成新闻获取。进行了如下改动：
- 添加了新闻推荐功能
- 重写了新闻pinia数据库
WARNING：如果运行中出现内存占用过大的情况，请报告。

feat(news):news recommend

---

frontend/pages/news_index/news_index.vue
frontend/stores/news_list.js

更新了社区主页。进行了如下改动：
- 增加了用户选择新闻排序的方法
- 略微修改了POST数据格式
- 略微修改了news_index的ui

feat(news): choose recommend type

---

frontend/pagesNews/news_detail/news_detail.vue

完善评论和回复功能。进行了如下改动：
- 为评论和回复添加作者信息

feat(news): comment and reply

---

frontend/pagesMy/my_home/my_home.vue
frontend/pagesNews/news_detail/news_detail.vue
frontend/pagesTool/recipe/recipe.vue

更新和问题修复，进行了如下改动：
- 更新了“我的创作”页的ui
- 增加了评论点赞、取消点赞、显示赞数的支持
- 修复了若干bug
TODO：
- 增加访问用户主页的支持

feat(my): new home page

---

frontend/locales/en.json
frontend/locales/zh-Hans.json
frontend/pages.json
frontend/pagesMy/login/login.vue
frontend/pagesMy/login_old/login_old.vue
frontend/pagesTool/recipe/recipe.vue

修复了登录页的结构。进行了如下改动：
- 隐藏了原有登录页（现改为“使用其他方式登录”）
- 设计了新登录页的ui
BREAKING：本次更新会改变原有的登录结构，如果登录出现问题，请立即说明

fix(login): login page

---

frontend/pagesMy/appSettings/appSettings.vue
frontend/pagesMy/userSettings/userSettings.vue
frontend/pagesNews/create_news/create_news.vue
frontend/pagesSetting/Idinfo/Idinfo.vue

为未开发功能封口。改动如下：
- 停止开发账号的绑定、设置密码、注销功能
- 停止开发清除数据功能
- 停止开发ai引入
- 停止开发黑名单、消息设置
- 停止开发字体调整

fix(seal): seal semi-developed functions

---

frontend/locales/zh-Hans.json
frontend/pages/news_index/news_index.vue
frontend/pagesNews/create_news/create_news.vue

fix(index): 改动功能名称

---

frontend/pagesNews/news_detail/news_detail.vue

fix(news)：第二次修改社区

---

frontend/locales/zh-Hans.json
frontend/pages.json
frontend/pagesNews/error_page/error_page.vue
frontend/pagesTool/foodPreferences/foodPreferences.vue
frontend/stores/news_list.js

同步1.0.2版本代码。修复了以下问题：
- 修复主页部分功能不能正常跳转的问题
- 修复饮食偏好无法使用的问题
- 增加了错误页
- 微调社区内容
微信小程序已更新1.0.2版本

fix(version): 1.0.2

---

frontend/locales/zh-Hans.json
frontend/pages/my_index/my_index.vue
frontend/pagesMy/favorites/favorites.vue
frontend/pagesMy/my_home/my_home.vue
frontend/pagesMy/stranger/stranger.vue
frontend/pagesNews/create_news/create_news.vue
frontend/pagesNews/edit_draft/edit_draft.vue
frontend/pagesNews/preview_draft/preview_draft.vue
frontend/pagesTool/add_food/add_food.vue
frontend/pagesTool/foodPreferences/foodPreferences.vue
frontend/pagesTool/food_recommend/food_recommend.vue
frontend/pagesTool/home_servant/home_servant.vue
frontend/pagesTool/myFamily/myFamily.vue
frontend/pagesTool/save_options/save_options.vue
frontend/pagesTool/stores/family.js
frontend/pagesTool/stores/food_list.js
frontend/stores/carbon_and_nutrition_data.js
frontend/stores/news_list.js
frontend/stores/user.js

添加了AI识图的前端框架。改动如下：
-更换了新的域名
-增加了图片入口

@feat: image2food frontend frame

---

frontend/pagesTool/add_food/add_food.vue

初步引入AI图片识别。进行了以下改动：
-增加了对于AI识图的支持
WARNING：
- 目前的框架只支持一种食物的识别
- 尚未对AI模型访问进行并发控制

feat(add_food): AI image recognition

---

model/model_classified.py
model/test_v2.py

fix: renew model training
